# Generated by Django 2.1.5 on 2019-01-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sate',
            new_name='state',
        ),
    ]
